// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8tCMN_yN51GeY-YdXLNJJYHs1dlpn7IM',
    appId: '1:148066986462:web:8c5d56b0b50a6db2f1d54f',
    messagingSenderId: '148066986462',
    projectId: 'digital-sport-market',
    authDomain: 'digital-sport-market.firebaseapp.com',
    storageBucket: 'digital-sport-market.appspot.com',
    measurementId: 'G-F9WWT6S3YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiwJ_ms1HVwhbLD4kJ6Bbg_fq8VdxR5F0',
    appId: '1:148066986462:android:c16101c2b8f7365df1d54f',
    messagingSenderId: '148066986462',
    projectId: 'digital-sport-market',
    storageBucket: 'digital-sport-market.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt_R2FoMM-4xkC_TIrZGz-yqLmmACJ_0g',
    appId: '1:148066986462:ios:1bc133b4eabcedf7f1d54f',
    messagingSenderId: '148066986462',
    projectId: 'digital-sport-market',
    storageBucket: 'digital-sport-market.appspot.com',
    iosBundleId: 'com.example.dspapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt_R2FoMM-4xkC_TIrZGz-yqLmmACJ_0g',
    appId: '1:148066986462:ios:bef94512d2cf356ff1d54f',
    messagingSenderId: '148066986462',
    projectId: 'digital-sport-market',
    storageBucket: 'digital-sport-market.appspot.com',
    iosBundleId: 'com.example.dspapp.RunnerTests',
  );
}
